spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school
    username: root
    password: admin
mybatis:
  mapper-locations: classpath:mapper/*.xml